### PR TITLE
fix(debugger): prevent memory leak in DAP setBreakpoints error path

### LINKED ISSUE #501: [BUG] Memory leak in debugger setBreakpoints when second parse fails
### Bug description

I found this while reviewing debugger request parsing for early-return cleanup.

In `c11_dap_handle_setBreakpoints`, `sourcename` is allocated with `c11_strdup(...)`.  
If the second `py_smarteval` fails, function returns before `PK_FREE(sourcename)`, leaking memory.

Observed behavior:

- Leak on malformed/invalid debugger breakpoint request in this error path.

This appears to occur in:

- `src/debugger/dap.c` in `c11_dap_handle_setBreakpoints()`

### Steps to reproduce

- upload the full stacktrace from your own code line to the error line  
  - Not a crash; this is a leak in debugger request error path.
- upload a minimum reproducible example

```python
# send malformed DAP setBreakpoints request causing:
# 1) first py_smarteval succeeds (allocates sourcename)
# 2) second py_smarteval fails (early return)
# then monitor debugger process memory across repeated requests
```

- additional information to help us reproduce the error
  - Leak is visible from code path inspection and missing cleanup on early return.
  - This was reproduced by code analysis on current `HEAD`.

### Environment information

- pocketpy's version: `2.1.8`
- platform string: `win32`
- 64-bit

### Suggested Fix

- Ensure `sourcename` is freed on all return paths (single-exit cleanup block or `goto cleanup`).
- Add a regression test for malformed DAP request handling.

### Contribution
I’d be happy to work on a fix and submit a PR.

### PR DESCRIPTION
**Pull request by ngoyal88**
## Description
Fixes a memory leak in the debugger's breakpoint request handler.

In `c11_dap_handle_setBreakpoints()`, if a client provides a valid source path but malformed breakpoint data, the first `py_smarteval` succeeds and allocates `sourcename` via `c11_strdup()`. However, when the second `py_smarteval` fails, the function returns early, permanently leaking the `sourcename` allocation.

This PR implements a `goto cleanup;` single-exit pattern to ensure `PK_FREE((void*)sourcename)` is reliably called on both the success and error paths. This avoids duplicating `PK_FREE` across multiple exits, centralizes the memory ownership release, and makes future modifications to the function safer against accidental leaks.

Fixes #501 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by lightovernight** [comment]
Maybe can we just simply add `PK_FREE((void*)sourcename);`  when second `py_smarteval` failed instead of using `goto` ?

File: src/debugger/dap.c [hunk 1]
```diff
@@ -108,14 +108,15 @@ inline static void c11_dap_build_Breakpoint(int id, int line, c11_sbuf* buffer)
...
+    const char* sourcename = NULL;
     if(!py_smarteval("_0['source']['path']", NULL, arguments)) {
         py_printexc();
         return;
     }
-    const char* sourcename = c11_strdup(py_tostr(py_retval()));
+    sourcename = c11_strdup(py_tostr(py_retval()));
     if(!py_smarteval("[bp['line'] for bp in _0['breakpoints']]", NULL, arguments)) {
         py_printexc();
-        return;
```
Comment (lightovernight) [inline src/debugger/dap.c:118]: maybe we can just add `PK_FREE((void*)sourcename);` there, and then this is the only change

**Review by lightovernight — APPROVED** [review]

**Review by lightovernight — APPROVED** [review]
